version: "3"
services:
  limbic_db:
    build:
      context: ./db/
    image: limbic:db
    container_name: limbic_db
    restart: always
    ports:
      - 27017:27017
    networks:
      - public-network

  limbic_server:
    build:
      context: ./backend
    image: limbic:server
    container_name: limbic_server
    depends_on:
      - limbic_db
    ports:
      - 8000:8000
    networks:
      - public-network

  limbic_client:
    build:
      context: ./frontend
    image: limbic:client
    container_name: limbic_client
    depends_on:
      - limbic_server
    ports:
      - 80:80
    networks:
      - public-network

networks:
  public-network:
    driver: bridge
